[package]
    edition = "2021"
    name    = "simple_db"
    version = "0.1.0"

[dependencies]
    anyhow = "1"
    nodb   = { path = "../../" }
    rand   = { version = "0.8", features = ["std"] }
    serde  = { version = "1", features = ["derive"] }
