[package]
    edition = "2021"
    name    = "bson"
    version = "0.1.0"

[dependencies]
    nodb  = { path = "../../" }
    rand  = { version = "0.8" }
    serde = { version = "1", features = ["derive"] }
